# Generated by Django 4.2.1 on 2023-05-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='Insurer',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='accident',
            new_name='promotions',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='household',
            new_name='travel_incon',
        ),
        migrations.RenameField(
            model_name='insuranceusp',
            old_name='card',
            new_name='insurance',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='legal',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='provider',
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurer', to='insurance.insurer'),
        ),
    ]
