# Generated by Django 4.2.1 on 2023-05-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='annualinterest',
            new_name='bonusinterestrate',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='cardassociation',
            new_name='interestrate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='incomeequirement',
        ),
        migrations.RemoveField(
            model_name='account',
            name='wirelesspayment',
        ),
    ]
