# Generated by Django 4.2.1 on 2023-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bonuscashrebate',
            field=models.TextField(null=True),
        ),
    ]
