# Generated by Django 4.2.1 on 2023-05-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.CharField(max_length=100, null=True)),
                ('doc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('disclosure', models.CharField(max_length=30, null=True)),
                ('execlusive', models.CharField(max_length=20, null=True)),
                ('badge_label', models.CharField(max_length=20, null=True)),
                ('badge_primary', models.CharField(max_length=20, null=True)),
                ('snippet', models.TextField(null=True)),
                ('snippet_img', models.CharField(max_length=200, null=True)),
                ('promotion', models.TextField(null=True)),
                ('keyfeatures', models.TextField(null=True)),
                ('annualinterest', models.TextField(null=True)),
                ('incomeequirement', models.TextField(null=True)),
                ('cardassociation', models.TextField(null=True)),
                ('wirelesspayment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentUsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd', models.CharField(max_length=30)),
                ('dt', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_usp', to='investment.investment')),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider', to='investment.provider'),
        ),
    ]
