# Generated by Django 4.2.1 on 2023-05-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='feature',
            field=models.BooleanField(null=True),
        ),
    ]
