# Generated by Django 4.2.1 on 2023-05-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_investment_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='annualinterest',
            new_name='accountopening',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='cardassociation',
            new_name='commissionfees',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='incomeequirement',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='wirelesspayment',
        ),
    ]
