# Generated by Django 4.2.1 on 2023-06-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='promotion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
