# Generated by Django 4.2.1 on 2023-06-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_alter_investment_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentusp',
            old_name='account',
            new_name='investment',
        ),
    ]
