# Generated by Django 4.2.1 on 2023-06-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_rename_account_investmentusp_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
