# Generated by Django 4.2.1 on 2023-05-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('disclosure', models.CharField(max_length=30, null=True)),
                ('execlusive', models.CharField(max_length=20, null=True)),
                ('badge_label', models.CharField(max_length=20, null=True)),
                ('badge_primary', models.CharField(max_length=20, null=True)),
                ('snippet', models.TextField(null=True)),
                ('snippet_img', models.CharField(max_length=200, null=True)),
                ('promotion', models.TextField(null=True)),
                ('keyfeatures', models.TextField(null=True)),
                ('repayment', models.TextField(null=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank', to='loans.bank')),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feature', to='loans.feature')),
            ],
        ),
        migrations.CreateModel(
            name='LoanUsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd', models.CharField(max_length=30)),
                ('dt', models.CharField(max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_usp', to='loans.loan')),
            ],
        ),
    ]
