# Generated by Django 4.2.1 on 2023-05-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanusp',
            old_name='card',
            new_name='loan',
        ),
    ]
