# Generated by Django 4.2.1 on 2023-05-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_card_loanusp_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='feature',
        ),
        migrations.AddField(
            model_name='loan',
            name='feature_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
