# Generated by Django 4.2.1 on 2023-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
