# Generated by Django 4.2.1 on 2023-06-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='feature_id',
            new_name='feature',
        ),
    ]
