# Generated by Django 4.2.1 on 2023-05-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.association')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200, null=True)),
                ('disclosure', models.CharField(max_length=30, null=True)),
                ('execlusive', models.CharField(max_length=20, null=True)),
                ('badge_label', models.CharField(max_length=20, null=True)),
                ('badge_primary', models.CharField(max_length=20, null=True)),
                ('snippet', models.TextField(null=True)),
                ('snippet_img', models.CharField(max_length=200, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.provider'),
        ),
    ]
