# Generated by Django 4.2.1 on 2023-05-23 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_association_remove_card_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.association'),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.provider'),
        ),
    ]
