# Generated by Django 4.2.1 on 2023-05-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_association_card_category_card_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetail',
            name='card',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
