# Generated by Django 4.2.1 on 2023-05-23 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_carddetail_card_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.association')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.provider')),
            ],
        ),
        migrations.AddField(
            model_name='carddetail',
            name='card',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
            preserve_default=False,
        ),
    ]
