# Generated by Django 4.2.1 on 2023-05-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_carddetail_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetail',
            name='image',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
