# Generated by Django 4.2.1 on 2023-05-24 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_cardusp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.provider'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cards.card'),
        ),
    ]
