# Generated by Django 4.2.1 on 2023-05-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_card_provider_alter_carddetail_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='association', to='cards.association'),
        ),
        migrations.AlterField(
            model_name='card',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider', to='cards.provider'),
        ),
    ]
