# Generated by Django 4.2.1 on 2023-05-24 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_card_association_alter_card_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='cardusp',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_usp', to='cards.card'),
        ),
    ]
