# Generated by Django 4.2.1 on 2023-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_carddetail_card_alter_cardusp_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='annualinterest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='badge_label',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='badge_primary',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cardassociation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='disclosure',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='execlusive',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='incomeequirement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='keyfeatures',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='promotion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='snippet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='snippet_img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='wirelesspayment',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='CardDetail',
        ),
    ]
