# Generated by Django 4.2.1 on 2023-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_card_annualinterest_card_badge_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='doc',
            field=models.TextField(null=True),
        ),
    ]
