# Generated by Django 4.2.1 on 2023-05-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_category_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
