# Generated by Django 4.2.1 on 2023-06-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_card_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='association',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
