# Generated by Django 4.2.1 on 2023-06-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_card_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='association',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
